name: CI Pipeline

on:
  push:
    branches: [ "main", "dev" ]
  pull_request:
    branches: [ "main" ]

jobs:
  test:
    runs-on: ubuntu-latest

    steps:
      # Chechout repo
      - name: Chechout code
        uses: actions/checkout@v3

      # Setup Python
      - name: Setup Python
        uses: actions/setup-python@v4
        with:
          python-version: "3.12"

      # Install dependencies
      - name: Install dependencies
        run: |
          pip install -r requirements.txt
          pip install pytest

      # Run tests
      - name: Run test
        run: |
          pytest -v